### ISSUE TITLE
[Feature request] Implementation of other input pairs

### ISSUE THREAD

**Issue by smartmic** [CoolProp/IF97#1]
Is it planned that all other input pairs apart from T,p will be implemented? I was trying to use this IF97 code but failed with `HmassP_INPUTS`.

**Comment by henningjp** [comment]
Working on this now.  Which input pairs are needed?  The backwards T(p,h), T(p,s), v(p,h), v(p,s) and p(h,s) equations? Or are there others?

**Comment by smartmic** [comment]
Yes, I was thinking of the backwards equations, especially missing T(p,h), T(p,s) and p(h,s).

**Comment by ibell** [comment]
We could certainly use the help to implement these backwards equations, though you should work with @henningjp on this.

**Comment by henningjp** [comment]
Half way there...

- [x] T(p,h) **implemented**
- [x] T(p,s) **implemented**
- [ ] p(h,s)

**Comment by smartmic** [comment]
These are great news, thank you!

**Comment by henningjp** [comment]
@smartmic, this should do it with PR #8.  I think this issue can be closed.

- [x] T(p,h) **implemented** _using ``IAPWS R7-97(2012)`` & ``IAPWS SR3-03(2014)`` Equations_
- [x] T(p,s) **implemented** _using ``IAPWS R7-97(2012)`` & ``IAPWS SR3-03(2014)`` Equations_
- [x] p(h,s) **implemented** _using ``IAPWS SR2-01(2014)`` & ``IAPWS SR4-04(2014)`` Equations_
- [x] T(h,s) **implemented** _using ``IAPWS SR4-04(2014)`` Equation for T(h,s) in Region 4_
