### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by henningjp** [CoolProp/IF97#10]
@ibell , I'm thinking that this is as far as I'll take IF97 for a while.  There are some other props that could be added, and there are non-iterative algebraic equations provided by IAPWS, but they are not "technically" part of the IF97 formulation (e.g. ionization constant, refractive index, static dialectric constant, etc.).

So, if I may suggest, we tag the last commit before I started messing with it (_commit bb22605 back in April 2015_), ``Version 1.0``.  This had all the thermodynamic state functions of (T,p), but still had that bug in the Cvmass() function (Coolprop/Coolprop#1150).

Recent additions include
- [x] Saturation Functions
- [x] Backward Functions of H and S
- [x] Transport Properties (viscosity and thermal conductivity)
- [x] Surface Tension  

This was all a fair bit of work and is probably a good place to put a stake in the ground and Tag ``Version 2.0`` as of the last P.R.  There are other enhancements that could be made, but this is a good stopping point for now.  I'd like to get these recent additions integrated into the IF97 Backend in CoolProp. 

What do you think?

**Comment by ibell** [comment]
Go for it!  I'm also fine if you want to just tag it with version 2.0 now and not worry about when version 1.0 was.  It might not be a terrible idea to have a little changelog as well for the IF97 standalone code.

I'm very appreciative of the numerous hours that you have put into developing the IF97 code and the MathCAD wrappers.  Your contribution is *exactly* what I had in mind when I made CoolProp open-source and invited the world in.

**Comment by henningjp** [comment]
OK.  I have a few tweaks yet that were needed to compile in with CoolProp.  I think I'll wait until the IF97 Backend is mostly done, in case there are more changes needed.

**Question:** I think I can just put a tag on the last commit in this next PR, correct?  Should it be an annotated tag or a lightweight tag?  Will those tags get pulled in with the PR?  Use a semantic version number (2.0.0)?

**Comment by henningjp** [comment]
@ibell, Nevermind.  I'll be putting in a P.R. with an annotated tag for v2.0.0 that contains a summary of the all the enhancements.

**Comment by ibell** [comment]
So I can ignore this issue then?

**Comment by henningjp** [comment]
Yes, sorry. Should have closed it.

**Comment by henningjp** [comment]
But don't ignore the other ones!  :smiley:
