### ISSUE TITLE
Tags not showing up in CoolProp/IF97

### ISSUE THREAD

**Issue by henningjp** [CoolProp/IF97#13]
@ibell , 
My v1.0.0 and v2.0.0 tags in my henningjp/IF97 repo aren't showing up in the CoolProp/IF97 repo.  Do you have to do something special to pull them up?  Create a release or something?

**Comment by ibell** [comment]
I think the tags don't get automatically pulled over with merges.  Can you tell me the SHA1 they should be tagged at and I can do that myself?

**Comment by henningjp** [comment]
$ git show v1.0.0
tag v1.0.0
Tagger: henningjp <jeff.p.henning@gmail.com>
Date:   Thu Jan 12 05:47:47 2017 -0500

Basic Thermodynamic Property Set

commit bb22605ba76fe060e692914a75740da5954a6e1d
Author: Ian Bell <ian.h.bell@gmail.com>
Date:   Fri Apr 3 23:04:57 2015 -0600

    make _Table5 static

================================================

$ git show v2.0.0
tag v2.0.0
Tagger: henningjp <jeff.p.henning@gmail.com>
Date:   Fri Jan 20 07:07:10 2017 -0500

New Features:

* Thermodynamic functions along the saturation curves
* Mathcad 15 wrapper for stand-alone IF97 usage and verification docs
* Optional compiler switch for more accurate Newtonw-Raphson calcs in Region 3
* Non-state dependent (trivial) property functions for water
* Backward Equations for T(p,h), T(p,s), P(h,s), and T(h,s)
* Transport Property functions (Viscosity, Thermal Conductivity, and Surface Tension)
* Bug fix in Cv formulation in Region 1

Contributors: ibell, henningjp

commit 8db7edd72649cc40e3bc0266fd2fb1be84ca30f6
Author: henningjp <jeff.p.henning@gmail.com>
Date:   Fri Jan 20 06:57:09 2017 -0500

    Provided a get_if97_version function and updated documentation

**Comment by ibell** [comment]
I think tags might not actually transfer when you do a PR/merge.  You might
need to add the tags manually to CoolProp/IF97.  I'm ready to make you an
admin on IF97 if you want.  Please use your power responsibly :)

**Comment by ibell** [comment]
This also seems pretty conclusive:
http://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request

**Comment by henningjp** [comment]
I'm fine with that.  I'll still defer to you on mods as the BDFL.

**Comment by ibell** [comment]
I think you are an admin now....

**Comment by henningjp** [comment]
So I've got tags in my local repo and up on my origin repo.  What's the best way to get them upstream?
1. git push --tags upstream    <== _this scares me a little_
2. create Releases on the Github interface at the intended commits?

**Comment by ibell** [comment]
Doing it in the github interface should be safe.  I haven't pushed tags
from the command line before, so I'm not sure how that works...

On Feb 23, 2017 3:59 AM, "Jeff Henning" <notifications@github.com> wrote:

So I've got tags in my local repo and up on my origin repo. What's the best
way to get them upstream?

   1. git push --tags upstream <== *this scares me a little*
   2. create Releases on the Github interface at the intended commits?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CoolProp/IF97/issues/13#issuecomment-281962047>, or mute
the thread

**Comment by henningjp** [comment]
:thumbsup:

**Comment by jowr** [comment]
Everything seems fine to me, please reopen if issues remain.

**Comment by ibell** [comment]
The issue was that tags applied in a fork need to be applied to the
upstream manually.  This was never really resolved, but I guess you can
close this issue.

**Comment by henningjp** [comment]
Sorry.  This WAS resolved.  I forgot to close the issue.  Tags for v1.0.0, v2.0.0, and v2.1.0 were manually applied.  You have to be an admin.  Then you can either push the tags manually to upstream from your local repo or create a release on GitHub from the web.  The release feature only lets you access a limit number of prior commits so I used that for 2.1.0, but had to resort to a manual push for the tags on the older commits.  All's well.
