### ISSUE TITLE
Saturation Curves Can Throw Invalid Exception

### ISSUE THREAD

**Issue by henningjp** [CoolProp/IF97#19]
The RegionOutput function in if97.h correctly throws an exception if a call is made with a (T, p) state that lies "exactly" on the saturation curve, since the vapor/liquid state is not known.  However, the saturation functions also make use of RegionOuput with a calculated saturated temperature, meaning the call is always on the saturation curve.  This should throw an exception (saturated state) even though the desired saturated liquid/vapor state is known and passed as a parameter.

Interestingly, this condition was not observed when compiled with VS2010 on Windows, as the state point was never "exactly" on the saturation curve.  Recent compilation with VS2015, however, threw many exceptions at specific pressure ranges when plotting thermodynamic values along the vapor/liquid saturation curves.  It is expected that optimization differences are the cause and other compilers could behave the same way.

Need to examine the IF97SatState parameter and only throw the exception when neither VAPOR nor LIQUID is specified, as when called by one of the saturation functions.  Otherwise return the correct result for the saturation state specified.

**Comment by rafuck** [comment]
Opened browser to write this issue %)
I need vaporization latent heat in dependence of pressure. And if I try to call 
```
inline double hliq_p(double p);
inline double hvap_p(double p);
```
to calculate difference between, I always get std::invalid_argument exception with message "Cannot use Region 4 with T and p as inputs". These functions will never work in current realization. For my purposes it is sufficient for this decision:
```
inline double hliq_p(double p){ return RegionOutput( IF97_HMASS, 0.99999*Tsat97(p), p, LIQUID); };
inline double hvap_p(double p){ return RegionOutput( IF97_HMASS, 1.00001*Tsat97(p), p, VAPOR); };
```

**Comment by henningjp** [comment]
Yep.  That's the issue. Not sure why it worked on VS2010 and partially worked in VS2015.  Anyway, I'll have a PR in this morning once I test it on VS2015.  Once corrected properly, it should work for all.

**Comment by henningjp** [comment]
@rafuck if you want to grab my changes to IF97.h and test it on MinGW, it's on https://github.com/henningjp/IF97/tree/R4_patch .  I'll PR it to CoolProp/IF97 later this morning once it's tested.

**Comment by rafuck** [comment]
@henningjp, yes in my case your patch works correctly
