### ISSUE TITLE
Question : a postgreSQL module for IF97 ?

### ISSUE THREAD

**Issue by mmouterde** [CoolProp/IF97#28]
I need a such lib wrapped as a postgreSQL module, Do you known if this kind of work already exists ?

**Comment by henningjp** [comment]
The only thing that exists so far is the raw header file and the Mathcad wrapper.  You are welcome to contribute.

**Comment by mmouterde** [comment]
Thanks for your reply !

**Comment by mmouterde** [comment]
@henningjp I could make a pull request to add my postgreSQL wrapper.
Could you give me guidelines/suggestions to locate my files ?

**Comment by henningjp** [comment]
Check the [IF97 Wiki](https://github.com/CoolProp/IF97/wiki) page for helpful instructions on contributing to the IF97 project.  Your wrapper would be located in your local repository under wrappers/postgreSQL under named branch from master.  The new branch should be pushed to your forked IF97 repository on Github and then make the pull request from there.  Again, see the [IF97 Wiki](https://github.com/CoolProp/IF97/wiki) for more details on this process.

**Comment by henningjp** [comment]
You can put a README.md (Markdown) file in that same location with a description and compiling and usage instructions as well.  Thanks!
