### ISSUE TITLE
IAPWS water static dielectric constant and Debye Huckel coefficients 

### ISSUE THREAD

**Issue by stuart-nolan** [CoolProp/IF97#33]
After a quick look through this IF97 repo, I don't see support for calculating these quantities (ref. [here](http://www.iapws.org/relguide/Dielec.html)). Is this the right place to check or are these values available elsewhere in CoolProp?

**Comment by ibell** [comment]
You are correct - that quantity is not available anywhere in CoolProp for
water.  Want to add it to the IF97 repo?

>

**Comment by stuart-nolan** [comment]
I can give it a try as I already have it in pure python code (using CoolProp HEOS).  May take a bit of time before I submit a PR for you to look at and that might not be what you want.  In any event, I want something different than I have now and I won't be bothered if you don't accept it.

**Comment by ibell** [comment]
Yes, a PR would be great.

>

**Comment by stuart-nolan** [comment]
Apologies for the ineptness of asking this question now (I'm neither a professional coder nor an expert in this field) but is CoolProp's IF97 repo the right place for this? Might there be a better repo in Coolprop to do this from?

The Fernandez et. al. 1997 reference I'm using cites "W. Wagner and A. Pruss, private communication (1995); J. Phys. Chem.
Ref. Data (submitted)" for the water EOS employed.  I'm assuming this refers to the "IAPWS-95 formulation" for the water EOS (apparently implemented in CoolProp's HEOS).  

Briefly looking over a paper or two on IF97, I don't see any reference to or requirement for calculating dielectric constants and/or Debye Huckel coefficients in IF97.  Also the applicable ranges for the quantities calculated in the Fernandez et. al. paper are 238 - 873 K at pressures up to 1200 MPa which extend beyond the max pressure for IF97 (100 MPa).  

I understand IF97 is related to/derived from/"faster than" the "IAPWS-95" formulation so I suppose using IF97 for the EOS isn't an issue provided the pressure is limited to the IF97 max and the resulting quantities reproduce those reported by Fernandez et al. to the specified significant figures.  But it seems a bit of waste not to have the ability to use CoolProp's HEOS for water.

**Comment by henningjp** [comment]
I have coded this in C++ and used it with the IF97 water properties functions with errors within the uncertainty in the IAPWS document.  However, as you mention, this limits the pressures to 100 MPa.  

I think the issue is that the static dielectric constant isn't built into CoolProp for any of the other fluids either, so there is no structure for it in the fluids files and no output string for retrieving that quantity.  Otherwise, it would be trivial to add this into the HEOS fluid file for water.  I think this would require a larger mod to CoolProp in general.

**Comment by stuart-nolan** [comment]
@henningjp Out of curiosity, does you implementation calculate the apparent molar compressibility (first partial derivative of the apparent molar volume with respect to pressure at constant temperature) and apparent molar heat capacity (first partial derivative of the apparent molar enthalpy with respect to temperature at constant pressure)?

My python implementation will reproduce the values reported in the Fernandez et. al. paper to its reported significant figures except  for these two quantities which are off by one or two (least) sig. figs. (which annoys me and implies I'm doing it wrong).

Thank you and @ibell for responding above.
