### ISSUE TITLE
Increase performance by substitution pow function with integer exponent

### ISSUE THREAD

**Issue by MarcSchiGom** [CoolProp/IF97#34]
I saw that the standard pow function is used for all power functions in IF97.h. Is it possible to substitute it, when the power value is an integer with an own function?

Example: Instead of pow(x, 5) we could use x * x * x * x * x. Or pow(x, -3) = 1.0 / (x * x * x)

Since the pow function is used very often in this way, it will increase performance significantly.

**Comment by ibell** [comment]
Yup, this is already done in CoolProp core. There is a function called powInt that can be borrowed.

**Comment by MarcSchiGom** [comment]
Perfect, thank you!
