### ISSUE TITLE
warning message for "A" variable - global declaration

### ISSUE THREAD

**Issue by theangkko** [CoolProp/IF97#42]
- visual studio 2022 community edition
- Windows 11 Pro 23H2

I get the  warning message when I build my Code in visual studio.
The result is same whatever I use as "AA" instead of "A"
I guess same variable used in another function. 

If I want to clear this warning message, it is the recommended solution to change variable name from "A" to another, isn't it?

<img width="805" alt="image" src="https://github.com/CoolProp/IF97/assets/75212211/32ea6ea0-2d9f-44c3-ac74-85881585a62f">

<img width="757" alt="image" src="https://github.com/CoolProp/IF97/assets/75212211/1c5f1329-412f-44f3-b65a-01182d04e165">

<img width="799" alt="image" src="https://github.com/CoolProp/IF97/assets/75212211/ec3b08e9-7aa5-4ade-bbc0-4e954894058f">

**Comment by henningjp** [comment]
@theangkko - Finally taking a look at this.  Glad you had a workaround.

I'm on Win11 and VS 2022 Community as well (Version 17.8.6).  I'm not seeing this error.  It should be a warning, but the definition within double p_T(double T) (which is public) should be a local definition and **_should_** mask the global variable (which is private).  I don't know why VS is throwing it as an error.

Based on your line numbers, you don't have the latest version of this file? There was an update in February, but it shouldn't have had an impact (I think) on what you are seeing.

I'll go ahead an patch this, but I am curios, 

1. Are you building in Release/x64 mode?  (I am)
2. What is your Warning level set to?  (Mine is level 3 - /W3)
3. So you have Treat Warnings As Errors set to something other than No (/WX-)?
4. What is your optimization level set to? (mine is set to /O2)
