### ISSUE TITLE
Newton-Raphson failing in parts of Region 3

### ISSUE THREAD

**Issue by henningjp** [CoolProp/IF97#44]
The Newton-Raphson iterative technique for `v(p,T)` is failing in some, but not all, of the verification points in the subregions in around the critical point.   All test points in the R3 subregions used to converge.  I think the last change to these routines was the efficiency changes with PR #17 .  Not sure I've run that verification since, but checking with some current work turned this up.  I'll go back and see what changed.

**Comment by henningjp** [comment]
Nope.  Verified as late as 2022.  Maybe VS2022 is causing it.

**Comment by henningjp** [comment]
Looks like PR #43 is causing some issues.  While the basic IF97 forward equations benefit from this optimized integer pow(x,i) function, the backward equations use power indexes that are not always integers.  This is causing a loss of data in the conversion and resulting in errors.  Also, the transport functions use the pow(x,y) functions, which were defaulting to the new integer pow(x,i) function and causing loss of data warnings and wrong answers.

There are fewer real powers needed than integer, so it was a simple fix to force these to use std::pow(x,y) in those locations rather than the new optimized pow(x,i) function.  This seems to be giving the correct verification values now.

Patch coming soon.

**Comment by ibell** [comment]
I always rename the specialized pow(int, double) when I fiddle with it to make clear it is not the standard one. I am surprised that is causing problems though unless it was improperly implemented.

**Comment by henningjp** [comment]
@ibell - I was surprised too that it didn't see that the second parameter was a double and call the correct overloaded function.  It was def calling the wrong one (local pow(double, int) and not std::pow(double, double) in those spots) and clipping the double exponents.  When I hover over it in VS2022, it shows that it's calling the int function.  Maybe there are optimization or linker switches that cause this behavior.  I might look into that.
