### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by listen0406** [CoolProp/IF97#47]
When debug the  IF97.cpp line 190, throw std::out_of_range("Enthalpy out of range"), it show than h2 = 2800 is out of range of the Hmax and Hmin
![图片1](https://github.com/CoolProp/IF97/assets/136311287/e37959d1-f0bf-4bc5-a7e3-b131bbe64b91)
![图片2](https://github.com/CoolProp/IF97/assets/136311287/ae56221d-e4ff-4842-beea-ea63b8b679ec)
![图片3](https://github.com/CoolProp/IF97/assets/136311287/f7475039-168f-47b7-bec6-a572f4d2ff91)
![图片4](https://github.com/CoolProp/IF97/assets/136311287/4cdd39c5-ba70-46bf-b0a8-ee5a646a5545)

**Comment by henningjp** [comment]
@listen0406 - Please post your command line output from running the test.  I just ran the latest master version and I do not get this error; the test runs fine.  I'm assuming you are seeing this issue in the Table 9 output.   Here's what I see for the Table 9 output using VS2022 to compile and run on Windows 11:

```
_________________________________________________
                 Region 2a, 2b, 2c
_________________________________________________
                      Table 9
_________________________________________________
     h/(kJ/kg)     s/(kJ/kg-K)       P/MPa
_________________________________________________
         2800         6.5       1.371012767e+00
         2800         9.5       1.879743844e-03
         4100         9.5       1.024788997e-01
_________________________________________________
         2800         6.0       4.793911442e+00
         3600         6.0       8.395519209e+01
         3600         7.0       7.527161441e+00
_________________________________________________
         2800         5.1       9.439202060e+01
         2800         5.8       8.414574124e+00
         3400         5.8       8.376903879e+01
_________________________________________________

```

There was an update just four days ago.  
* Please make sure you have the latest commits.
* Please post your entire output

**Comment by listen0406** [comment]
> @listen0406 - Please post your command line output from running the test. I just ran the latest master version and I do not get this error; the test runs fine. I'm assuming you are seeing this issue in the Table 9 output. Here's what I see for the Table 9 output using VS2022 to compile and run on Windows 11:
> 
> ```
> _________________________________________________
>                  Region 2a, 2b, 2c
> _________________________________________________
>                       Table 9
> _________________________________________________
>      h/(kJ/kg)     s/(kJ/kg-K)       P/MPa
> _________________________________________________
>          2800         6.5       1.371012767e+00
>          2800         9.5       1.879743844e-03
>          4100         9.5       1.024788997e-01
> _________________________________________________
>          2800         6.0       4.793911442e+00
>          3600         6.0       8.395519209e+01
>          3600         7.0       7.527161441e+00
> _________________________________________________
>          2800         5.1       9.439202060e+01
>          2800         5.8       8.414574124e+00
>          3400         5.8       8.376903879e+01
> _________________________________________________
> ```
> 
> There was an update just four days ago.
> 
> * Please make sure you have the latest commits.
> * Please post your entire output

Thank you! The latest version is OK now.

**Comment by henningjp** [comment]
I'm glad you sorted it out.  There were some issues introduced that have recently fixed.  This may have been the culprit.
