### ISSUE TITLE
IF97 Reverse Function Errors Reported Very Near Saturation

### ISSUE THREAD

**Issue by henningjp** [CoolProp/IF97#48]
Several issues have been reported where IF97 returns unphysical values in the single-phase regions very near the saturation curve.  When the reverse functions of T(p,h) and T(p,s) are used to calculate other properties using pressure and the calculated temperature, T, the other properties can arbitrarily return values from the wrong liquid/vapor phase.  This has been noted in CoolProp issues CoolProp/CoolProp#1918 and CoolProp/CoolProp#2334 when using the IF97 backend.

Based on [IAPWS R7-97(2012)](http://www.iapws.org/relguide/IF97-Rev.pdf) (Eqn. 12 & 14) the uncertainty in the Temperature returned from T(p,h) and T(p,s) can be ±25mK.  This is enough variation that a Liquid (Region 1) entropy/enthalpy very near the saturation curve can return a temperature that is actually below/right of the saturation curve in the Vapor (Region 2) phase.  Using this temperature and the specified pressure to calculate any other property would return values from the wrong phase, which can be grossly incorrect.

This is demonstrated below using the Mathcad interface to plot Saturation Entropies along the saturation pressure curve minus a very small delta of 1E-6 J/kg-K.  As shown in the plot below, by subtracting the temperature result from a direct calculation of Tsat(p), some of the temperatures end up above the saturation curve in Region 1 and some end up slightly below the saturation curve in Region 2.

![image](https://github.com/CoolProp/IF97/assets/17114032/5fb3324d-2b26-4e30-b9a2-9d2cc4bcc7ed)

The same thing happens along the liquid saturation curve and is shown to occur in the T(p,h) calculation as well for both curves.  

> **NOTE:** The uncertainty in the short section of the saturation curve that lies in Region 3 has a much smaller error (±0.5 mK), but that the error can still occur, just much closer to the saturation curve.  This uncertainty is documented in [IAPWS SR3-03(2014)](http://www.iapws.org/relguide/Supp-Tv(ph,ps)3-2014.pdf) (Tables 21 & 22).

The conclusion is that 

1. these functions should never return a temperature from the opposite region of the (p,s) or (p,h) state point.
2. the simplest fix is to limit the return temperature value by the saturation curve value, Tsat(p), depending on the region of the input state point.  
 
A PR to fix this issue, making the IF97 reverse function implementation more robust, is in progress and will be submitted shortly.

**Comment by ibell** [comment]
Thanks for sorting this out
